name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # 当贡献者更新 PR 且不再修改某些目录时，自动移除不再匹配的标签
          sync-labels: true
